config/routes.rb
Rails.application.routes.draw do


    # root 'welcome#index'
     # get 'users/profile/:id' => 'users#profile'
     #  get 'users/edit/:id/edit' => 'users#edit'
     #   get 'users/update/:id' => 'users#update'
    
     # resources :profiles
 
   get 'show/:id' => 'users#show'
   put 'update/:id' => 'users#update'
   get 'export/:id' => 'users#export'


  root 'home#index'
  devise_for :users, :controllers => { sessions: 'sessions' }
    
  
  resources :conversations, only: [:create] do

   member do
      post :close
    end

   end
 
   resources :conversations, only: [:create] do
    resources :messages, only: [:create]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	 # mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   mount_uploader :image, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :messages
        has_many :conversations, foreign_key: :sender_id

     
   def online?
    if current_sign_in_at.present? 
      last_sign_out_at.present? ? current_sign_in_at > last_sign_out_at : true
    else
      false
    end
  end


def self.find_for_database_authentication(conditions={})
  find_by(username: conditions[:email]) || find_by(email: conditions[:email])
end


def filename
  if original_filename
    if model && model.read_attribute(:image).present? #or whatever you call your column
      model.read_attribute(:image)
    else
      # create new filename however you're doing it
    end
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
   protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname,:username,:phone_number,:last_sign_out_at,:age,:phone_number])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:fullname, :username, :phone_number, :last_sign_out_at, :current_password, :image,:about_us,:age,:country,:city_town,:resident_address,:my_football_possition) }
  end

end

app/controllers/concerns/session_controller.rb
class SessionsController < Devise::SessionsController

  def destroy
    current_user.update_attribute(:last_sign_out_at, Time.now)
    super
  end
  
  def self.find_for_authentication(conditions)
  conditions = ["username = ? or email = ?", conditions[authentication_keys.first], conditions[authentication_keys.first]]
  # raise StandardError, conditions.inspect
  super
end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])
    
    add_to_conversations unless conversated?

    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])
 
    session[:conversations].delete(@conversation.id)
 
    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:conversations] ||= []
 
    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.includes(:recipient).find(params[:conversation_id])
    @message = @conversation.messages.create(message_params)

    respond_to do |format|
      format.js
    end
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :body)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
    # authorize! :delete, @user
    respond_to :html, :json

    def show
     @user = User.find(params[:id])
   end
   
   def edit
     @user = User.find(params[:id])
   end

    def update

      @user = User.find params[:id]
      @user.update_attributes(message_params)
      respond_with @user
  
    #   format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
    #   format.json { respond_with_bip(@user) }
    # else
    #   format.html { render :action => "edit" }
    #   format.json { respond_with_bip(@user) }
    # end
  end
   def destroy
   end
   private

  def message_params
       params.require(:user).permit(:fullname, :username, :phone_number, :last_sign_out_at, :current_password, :image,:about_us,:age,:country,:city_town,:resident_address,:my_football_possition) 

  end
  end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def destroy
    current_user.update_attribute(:last_sign_out_at, Time.now)
    super
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:destroy]
def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end


     private
    def set_user
      @user = User.find(params[:id])
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_conversation.html.erb
<li> 
<div class="col-md-4">
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-heading">
      <%= link_to conversation.opposed_user(user).email, '', class: 'toggle-window' %>
      <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
    </div>
    
    <div class="panel-body" style="display: none;">
      <div class="messages-list">
        <ul>

          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>
      <%= form_for [conversation, conversation.messages.new], remote: true do |f| %>
        <%= f.hidden_field :user_id, value: user.id %>
        <%= f.text_area :body, class: "form-control" %>
        <%= f.submit "Send", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/home/index.html.erb
<!-- <div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
           <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div> -->

<!--
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
-->

<div class="container">
<div class="row profile">
  <div class="col-md-3">
    <div class="profile-sidebar">
      <!-- SIDEBAR USERPIC -->
      <div class="profile-userpic">
        <!-- <img src="https://i.ytimg.com/vi/jJRj27LiqGo/maxresdefault.jpg" class="img-responsive" alt=""> -->
        <%if current_user.image.url(:thumb).present? %>
        <%= image_tag current_user.image.url(:thumb)%>
        <%else%>
       <%=image_tag 'pic.png', :class=>"img-circle",:alt=>"Cinque Terre",:width=>"50" ,:height=>"50" %>
        <%end%>
      </div>
      <!-- END SIDEBAR USERPIC -->
      <!-- SIDEBAR USER TITLE -->
      <div class="profile-usertitle">
        <div class="profile-usertitle-name">
         <%= current_user.email%>
        </div>
        <!-- <div class="profile-usertitle-job">
          Developer
        </div> -->
      </div>
      <!-- END SIDEBAR USER TITLE -->
      <!-- SIDEBAR BUTTONS -->
      <!-- <div class="profile-userbuttons">
        <button type="button" class="btn btn-success btn-sm">Follow</button>
        <button type="button" class="btn btn-danger btn-sm">Message</button>
      </div> -->
      <!-- END SIDEBAR BUTTONS -->
      <!-- SIDEBAR MENU -->
      <div class="profile-usermenu">
        <ul class="nav">
          <li class="active">
            <a href="#">
            <!-- <i class="glyphicon glyphicon-home"></i> -->
            My Profile </a>
          </li>
          <li>
            <a href="#">
            <!-- <i class="glyphicon glyphicon-user"></i> -->
            Message </a>
          </li>
          <li>
            <a href="#" target="_blank">
            <!-- <i class="glyphicon glyphicon-ok"></i> -->
            Connection </a>
          </li>
          <li>
            <a href="#">
            <!-- <i class="glyphicon glyphicon-flag"></i> -->
            Find Agent </a>
          </li>
          <li>
            <a href="#">
            <!-- <i class="glyphicon glyphicon-flag"></i> -->
            Find Player </a>
          </li>
          <li>
            <a href="#">
            <button type="button" class="btn btn-success btn-sm">Unverfied</button>
            <!-- <i class="glyphicon glyphicon-flag"></i> -->
            </a>
          </li>
        </ul>
      </div>
      <!-- END MENU -->
    </div>
  </div>
  <div class="col-md-9">
        <div class="profile-content">
       Some user related content goes here...
       <!-- <ul id="conversations-list">
      <% @conversations.each do |conversation| %>

        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">chat</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
           <li><%= link_to user.username, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul> -->
      </div>
    </div>
        </div>
  </div>
</div>
</div>
<center>
<strong>Powered by <a href="http://j.mp/metronictheme" target="_blank">KeenThemes</a></strong>
</center>
<br>
<br>


<style type="text/css">
  /***
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
***/

body {
  background: #F1F3FA;
}

/* Profile container */
.profile {
  margin: 20px 0;
}

/* Profile sidebar */
.profile-sidebar {
  padding: 20px 0 10px 0;
  background: #fff;
}

.profile-userpic img {
  float: none;
  margin: 0 auto;
  width: 50%;
  height: 50%;
  -webkit-border-radius: 50% !important;
  -moz-border-radius: 50% !important;
  border-radius: 50% !important;
}

.profile-usertitle {
  text-align: center;
  margin-top: 20px;
}

.profile-usertitle-name {
  color: #5a7391;
  font-size: 16px;
  font-weight: 600;
  margin-bottom: 7px;
}

.profile-usertitle-job {
  text-transform: uppercase;
  color: #5b9bd1;
  font-size: 12px;
  font-weight: 600;
  margin-bottom: 15px;
}

.profile-userbuttons {
  text-align: center;
  margin-top: 10px;
}

.profile-userbuttons .btn {
  text-transform: uppercase;
  font-size: 11px;
  font-weight: 600;
  padding: 6px 15px;
  margin-right: 5px;
}

.profile-userbuttons .btn:last-child {
  margin-right: 0px;
}
    
.profile-usermenu {
  margin-top: 30px;
}

.profile-usermenu ul li {
  border-bottom: 1px solid #f0f4f7;
}

.profile-usermenu ul li:last-child {
  border-bottom: none;
}

.profile-usermenu ul li a {
  color: #93a3b5;
  font-size: 14px;
  font-weight: 400;
}

.profile-usermenu ul li a i {
  margin-right: 8px;
  font-size: 14px;
}

.profile-usermenu ul li a:hover {
  background-color: #fafcfd;
  color: #5b9bd1;
}

.profile-usermenu ul li.active {
  border-bottom: none;
}

.profile-usermenu ul li.active a {
  color: #5b9bd1;
  background-color: #f6f9fb;
  border-left: 2px solid #5b9bd1;
  margin-left: -2px;
}

/* Profile Content */
.profile-content {
  padding: 20px;
  background: #fff;
  min-height: 460px;
}
</style>




<script type="text/javascript">
  $(document).ready(function() {

  $('.panel-heading').click(function() {
   $('.panel-body').toggle();//Form shows on button click

   });
 });
</script>

<style type="text/css">
.panel-body
{height:300px;overflow:auto;}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoFootball</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
    <div class="container">
    <%= yield %>



    <% if current_user %>
      <div class="container">
        <div class=row>
          <div class="col-md-2 pull-right" >
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">People online<span class="glyphicon glyphicon-minus-sign minus-sign" style="float: right"></span><span class="glyphicon glyphicon-plus-sign plus-sign" style="float: right; display:none;"></span></h3>


              </div>
              <div class="panel-body" style="height:300px; overflow:auto;">
                <%@users = User.all.where.not(id: current_user).where('username is not null')%>
                <ul>
                 <% @users.each do |user| %>
                    <% if user.online?%>
                      <div class="" style="float: right;
                        line-height: 20px;
                        margin: 0 1px 0 4px;
                        text-align: right">
                       <span style="background: rgb(66, 183, 42); border-radius: 50%; display: inline-block; height: 6px; margin-left: 4px; width: 6px;"></span>
                      </div>
                      <a href="/conversations?user_id=<%=user.id %>" data-remote=true data-method= post>


                      <span style="overflow: hidden;padding-left:8px;
                      text-overflow: ellipsis;
                      white-space: nowrap;">
                      <%if user.image.url(:small_thumb).present? %>
                     <%= image_tag user.image.url(:small_thumb)%>
                      <%else%>
                      <%=image_tag 'pic.png', :class=>"img-circle",:alt=>"Cinque Terre",:width=>"30" ,:height=>"30" %>
                      <%end%>&nbsp;&nbsp;&nbsp;
                      <%= user.fullname.split.first%>
                       <p>Online</p>
                      </span><hr/>
                      </a>

                     <% else %>
                     <span style="color: #fff; border-radius: 50%; display: inline-block; height: 6px; margin-left: 4px; width: 6px; float: right; "></span>
                      <a href="/conversations?user_id=<%=user.id %>" data-remote=true data-method= post>


                      <span style="overflow: hidden;padding-left:8px;
                      text-overflow: ellipsis;

                      white-space: nowrap;">
                     <%if user.image.url(:thumb).present? %>
                     <%= image_tag user.image.url(:thumb)%>
                      <%else%>
                      <%=image_tag 'pic.png', :class=>"img-circle",:alt=>"Cinque Terre",:width=>"30" ,:height=>"30" %>
                      <%end%>&nbsp;&nbsp;&nbsp;
                      <%= user.fullname.split.first%><%total_secand=Time.now-(user.last_sign_out_at)%>
                      <%seconds = total_secand % 60%>
                      <%hours=total_secand/(60 * 60)%>
                      <%minutes = ((total_secand / 60)%60) %>
                      <p> Last seen &nbsp;<%=format("%02d", hours)%>h
                      <%=format("%02d", minutes)%>m
                       <%=format("%02d", seconds)%>s ago</p>
                     </a>
                    <% end %>
                 <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <div class="">

        <div id="conversations-list">
          <%session[:conversations] ||= []%>
         <% @conversations = Conversation.includes(:recipient, :messages)
          .find(session[:conversations])%>
         <% @conversations.each do |conversation| %>
          <%= render 'conversations/conversation', conversation: conversation, user: current_user%>
          <% end %>
        </div>
      </div>
    </div>

  </body>
</html>

<style>
p {
    font-size: 10px;
}
</style>

app/views/messages/_message.html.erb
<li>
  <div class="row">
    <div class="<%= user.id == message.user_id ? 'message-sent' : 'message-received' %>">
      <%= message.body %>
    </div>
  </div>
</li>

app/views/messages/create.js.erb
var conversation = $('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
conversation.find('.messages-list').find('ul').append("<%= j(render 'messages/message', message: @message, user: current_user) %>");
conversation.find('textarea').val('');

app/views/users/show.html.erb
<h4><center>My Profile</center></h4>

<div class="container">
<div class="row profile">
  <div class="col-md-3">
    <div class="profile-sidebar">
      <!-- SIDEBAR USERPIC -->
      <div class="profile-userpic">
        <!-- <img src="https://i.ytimg.com/vi/jJRj27LiqGo/maxresdefault.jpg" class="img-responsive" alt=""> -->
        <%if current_user.image.url(:thumb).present? %>
        <%= image_tag current_user.image.url(:thumb)%>
        <%else%>
       <%=image_tag 'pic.png', :class=>"img-circle",:alt=>"Cinque Terre",:width=>"50" ,:height=>"50" %>
        <%end%>
      </div>
      <!-- END SIDEBAR USERPIC -->
      <!-- SIDEBAR USER TITLE -->
      <div class="profile-usertitle">
        <div class="profile-usertitle-name">
         <%= current_user.email%>
        </div>
        <!-- <div class="profile-usertitle-job">
          Developer
        </div> -->
      </div>

<div class="profile-usermenu">
        <ul class="nav">
          <li class="active">
           <!--  <a href=" /users/profile"> -->
           <%#=link_to 'my Profile',user_path(:id=>current_user.id)%>
            <!-- <i class="glyphicon glyphicon-home"></i> -->
           </a>
          </li>
          <li>
            <a href="#">
            <!-- <i class="glyphicon glyphicon-user"></i> -->
            Message </a>
          </li>
          <li>
            <a href="#" target="_blank">
            <!-- <i class="glyphicon glyphicon-ok"></i> -->
            Connection </a>
          </li>
          <li>
            <a href="#">
            <!-- <i class="glyphicon glyphicon-flag"></i> -->
            Find Agent </a>
          </li>
          <li>
            <a href="#">
            <!-- <i class="glyphicon glyphicon-flag"></i> -->
            Find Player </a>
          </li>
          <li>
            <a href="#">
            <button type="button" class="btn btn-success btn-sm">verfied</button>
            <!-- <i class="glyphicon glyphicon-flag"></i> -->
            </a>
          </li>
        </ul>
      </div>
      <!-- END MENU -->
   </div>
   </div>
<div class="col-md-6">
<div class="row">
<div class=col-md-5><h5>about me</h5><%#=@user.about_us%></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>




<div class="row">
<div class=col-md-5><h5>my age:</h5><%= best_in_place @user, :age, :as => :input,url: "/update/#{@user.id}" %></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>


<div class="row">
<div class=col-md-5><h5>country</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>


<div class="row">
<div class=col-md-5><h5>city/town</h5><%= best_in_place @user, :city_town, :as => :input,url: "/update/#{@user.id}" %></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>


<div class="row">
<div class=col-md-5><h5>resident address</h5><%= best_in_place @user, :country, :as => :input,url: "/update/#{@user.id}" %></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>

<div class="row">
<div class=col-md-5><h5>photos</h5><%= best_in_place @user, :phone_number, :as => :input ,url: "/update/#{@user.id}" %>
</div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>

<div class="row">
<div class=col-md-5><h5>education background</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>

<div class="row">
<div class=col-md-5><h5>current previous team(s)</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>

<div class="row">
<div class=col-md-5><h5>my favorate leagues/team(s)</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>

<div class="row">
<div class=col-md-5><h5>my favorate role model(s)</h5></div>

</div>

<div class="row">
<div class=col-md-5><h5>my favorie football coach(es)</h5></div>

</div>

<div class="row">
<div class=col-md-5><h5>my football possition</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div><br/>
<h4><center>Social link</center></h4>

<div class="row">
<div class=col-md-5><h5>facebook</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>

<div class="row">
<div class=col-md-5><h5>twiter</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>

<div class="row">
<div class=col-md-5><h5>instagram</h5></div>
<div class=col-md-2><%=link_to 'edit','#'%></div>
</div>
   </div>
   </div>

   <center><%=link_to "PdF open","/export/{@user.id}",:class=>"btn btn-primary"%></center>



























<style type="text/css">

body {
  background: #F1F3FA;
}

/* Profile container */
.profile {
  margin: 20px 0;
}

/* Profile sidebar */
.profile-sidebar {
  padding: 20px 0 10px 0;
  background: #fff;
}

.profile-userpic img {
  float: none;
  margin: 0 auto;
  width: 50%;
  height: 50%;
  -webkit-border-radius: 50% !important;
  -moz-border-radius: 50% !important;
  border-radius: 50% !important;
}

.profile-usertitle {
  text-align: center;
  margin-top: 20px;
}

.profile-usertitle-name {
  color: #5a7391;
  font-size: 16px;
  font-weight: 600;
  margin-bottom: 7px;
}

.profile-usertitle-job {
  text-transform: uppercase;
  color: #5b9bd1;
  font-size: 12px;
  font-weight: 600;
  margin-bottom: 15px;
}

.profile-userbuttons {
  text-align: center;
  margin-top: 10px;
}

.profile-userbuttons .btn {
  text-transform: uppercase;
  font-size: 11px;
  font-weight: 600;
  padding: 6px 15px;
  margin-right: 5px;
}

.profile-userbuttons .btn:last-child {
  margin-right: 0px;
}
    
.profile-usermenu {
  margin-top: 30px;
}

.profile-usermenu ul li {
  border-bottom: 1px solid #f0f4f7;
}

.profile-usermenu ul li:last-child {
  border-bottom: none;
}

.profile-usermenu ul li a {
  color: #93a3b5;
  font-size: 14px;
  font-weight: 400;
}

.profile-usermenu ul li a i {
  margin-right: 8px;
  font-size: 14px;
}

.profile-usermenu ul li a:hover {
  background-color: #fafcfd;
  color: #5b9bd1;
}

.profile-usermenu ul li.active {
  border-bottom: none;
}

.profile-usermenu ul li.active a {
  color: #5b9bd1;
  background-color: #f6f9fb;
  border-left: 2px solid #5b9bd1;
  margin-left: -2px;
}

/* Profile Content */
.profile-content {
  padding: 20px;
  background: #fff;
  min-height: 460px;
}

	h4
	{
		color: green;
	}
	h5
	{
		color: green;
	}
</style>

<<!-- script type="text/javascript">
  $(document).ready(function() {

  $('.panel-heading').click(function() {
   $('.panel-body').toggle();//Form shows on button click

   });
 });
</script> -->